sudo: false
language: node_js
node_js:
  - "8.0.0"
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - yarn
  - yarn global add http-server
before_script:
  - http-server &
script: yarn run travis
